import type { MemoryEvent, MemoryRetrievalOutcome } from "@companion/memory";
import {
  createP8Projection,
  type P8AuthoredInvariant,
  type P8EpistemicState,
  type P8IdentityAddress,
  type P8IdentityProjection,
  type P8PersonaProjection,
  type P8ProvenanceReference,
  type P8SemanticProvenanceReference
} from "./index.js";
import {
  createP8AuthorizedEvidence,
  createP8EvidenceAccessOutcome,
  createP8EvidenceInterpretation,
  type P8AuthorizedEvidence,
  type P8EvidenceAccessOutcome,
  type P8EvidenceAccessStatus,
  type P8EvidenceInterpretation,
  type P8EvidenceInterpretationInput,
  type P8EvidenceProvenanceReference,
  type P8EvidenceScopeReference,
  type P8InterpretationEvidenceLinkInput
} from "./evidence.js";

/** The pure adapter/projection contract introduced by P8-1C. */
export const P8_1C_VERSION = "p8-1c.v1" as const;

export type P8RecentConversationMessageInput = Readonly<{
  /** A stable identity supplied by the bounded conversation source. */
  messageReference: string;
  role: "user" | "assistant";
  content: string;
  scopeReference: P8EvidenceScopeReference;
  /** The source-supplied time, if one exists. Never generated by this adapter. */
  suppliedAt?: string;
}>;

export type P8RecentConversationInput = Readonly<{
  /** Messages must already be bounded to the current session/context window. */
  messages: readonly P8RecentConversationMessageInput[];
  maxMessages: number;
  maxCharacters: number;
  /** Exclusion is by message identity, never by matching content. */
  currentMessageReference?: string;
}>;

export type P8MemoryEvidenceAdapterInput = Readonly<{
  outcome: MemoryRetrievalOutcome;
  /** The caller supplies the scope authorized for this evidence request. */
  expectedScopeReference: P8EvidenceScopeReference;
}>;

export type P8InterpretationCandidateInput = Readonly<{
  domain: P8EvidenceInterpretationInput["domain"];
  meaning?: string;
  evidenceLinks?: readonly P8InterpretationEvidenceLinkInput[];
}>;

export type P8EvidenceAdapterInput = Readonly<{
  address: P8IdentityAddress;
  authoredInvariants: readonly P8AuthoredInvariant[];
  expectedScopeReference: P8EvidenceScopeReference;
  longTerm: MemoryRetrievalOutcome;
  recentConversation?: P8RecentConversationInput;
  /** Candidates are explicit semantic input; the adapter never creates them. */
  interpretationCandidates?: readonly P8InterpretationCandidateInput[];
}>;

export type P8AdaptedEvidenceAccess = Readonly<{
  channel: "LONG_TERM_EVIDENCE" | "RECENT_CONVERSATION";
  outcome: P8EvidenceAccessOutcome;
}>;

export type P8EvidenceChannelProjection = Readonly<{
  accessStatus: P8EvidenceAccessStatus;
  /** Evidence without an explicit interpretation does not become known meaning. */
  status: P8EpistemicState;
  evidenceCount: number;
  provenance: readonly P8EvidenceProvenanceReference[];
}>;

export type P8ReadOnlyEvidenceProjection = Readonly<{
  projectionVersion: typeof P8_1C_VERSION;
  address: P8IdentityAddress;
  identity: P8IdentityProjection;
  persona: P8PersonaProjection;
  longTermEvidence: P8EvidenceChannelProjection;
  recentConversation?: P8EvidenceChannelProjection;
  interpretations: readonly P8EvidenceInterpretation[];
  provenance: readonly P8SemanticProvenanceReference[];
}>;

export function adaptP8MemoryRetrievalOutcome(
  input: P8MemoryEvidenceAdapterInput
): P8AdaptedEvidenceAccess {
  const expectedScopeReference = validateScopeReference(input.expectedScopeReference);
  const outcome = input.outcome;
  const evidence = outcome.events.map((event) => adaptMemoryEvent(event, expectedScopeReference));

  switch (outcome.status) {
    case "ok":
      if (evidence.length === 0) {
        throw new Error("P8 memory adapter received ok retrieval with no events.");
      }
      return Object.freeze({
        channel: "LONG_TERM_EVIDENCE" as const,
        outcome: createP8EvidenceAccessOutcome({
          status: "SUCCESS_WITH_EVIDENCE",
          evidence
        })
      });
    case "empty":
      if (evidence.length > 0) {
        throw new Error("P8 memory adapter received empty retrieval with events.");
      }
      return Object.freeze({
        channel: "LONG_TERM_EVIDENCE" as const,
        outcome: createP8EvidenceAccessOutcome({
          status: "SUCCESS_WITH_NO_RELEVANT_EVIDENCE",
          evidence: []
        })
      });
    case "partial":
      return Object.freeze({
        channel: "LONG_TERM_EVIDENCE" as const,
        outcome: createP8EvidenceAccessOutcome({
          status: "PARTIAL",
          evidence
        })
      });
    case "unavailable":
    case "error":
      if (evidence.length > 0) {
        throw new Error(`P8 memory adapter received ${outcome.status} retrieval with events.`);
      }
      return Object.freeze({
        channel: "LONG_TERM_EVIDENCE" as const,
        outcome: createP8EvidenceAccessOutcome({
          status: outcome.status === "unavailable" ? "UNAVAILABLE" : "ERROR",
          evidence: []
        })
      });
  }
}

export function adaptP8RecentConversation(
  input: P8RecentConversationInput,
  expectedScopeReference: P8EvidenceScopeReference
): P8AdaptedEvidenceAccess {
  const expectedScope = validateScopeReference(expectedScopeReference);
  validateNonNegativeInteger(input.maxMessages, "recent conversation maxMessages");
  validateNonNegativeInteger(input.maxCharacters, "recent conversation maxCharacters");

  const messages = input.messages.filter(
    (message) => message.messageReference !== input.currentMessageReference
  );
  if (messages.length > input.maxMessages) {
    throw new Error("P8 recent conversation input exceeds maxMessages.");
  }

  const characterCount = messages.reduce((total, message) => total + message.content.length, 0);
  if (characterCount > input.maxCharacters) {
    throw new Error("P8 recent conversation input exceeds maxCharacters.");
  }

  const evidence = messages.map((message) => adaptRecentMessage(message, expectedScope));
  return Object.freeze({
    channel: "RECENT_CONVERSATION" as const,
    outcome: createP8EvidenceAccessOutcome({
      status: evidence.length > 0 ? "SUCCESS_WITH_EVIDENCE" : "SUCCESS_WITH_NO_RELEVANT_EVIDENCE",
      evidence
    })
  });
}

export function createP8EvidenceAdapterProjection(
  input: P8EvidenceAdapterInput
): P8ReadOnlyEvidenceProjection {
  const expectedScopeReference = validateScopeReference(input.expectedScopeReference);
  const authoredProjection = createP8Projection({
    address: input.address,
    authoredInvariants: input.authoredInvariants
  });
  const longTerm = adaptP8MemoryRetrievalOutcome({
    outcome: input.longTerm,
    expectedScopeReference
  });
  const recent =
    input.recentConversation === undefined
      ? undefined
      : adaptP8RecentConversation(input.recentConversation, expectedScopeReference);
  const allEvidence = [
    ...longTerm.outcome.evidence,
    ...(recent === undefined ? [] : recent.outcome.evidence)
  ];
  assertUniqueEvidenceReferences(allEvidence);

  const interpretations = (input.interpretationCandidates ?? []).map((candidate) => {
    const accessStatus = accessStatusForCandidate(candidate, longTerm, recent, allEvidence);
    return createP8EvidenceInterpretation({
      domain: candidate.domain,
      ...(candidate.meaning === undefined ? {} : { meaning: candidate.meaning }),
      access: {
        status: accessStatus,
        evidence: allEvidence
      },
      ...(candidate.evidenceLinks === undefined ? {} : { evidenceLinks: candidate.evidenceLinks })
    });
  });

  const longTermProjection = projectEvidenceChannel(longTerm.outcome);
  const recentProjection =
    recent === undefined ? undefined : projectEvidenceChannel(recent.outcome);
  const provenance = uniqueProvenance([
    ...authoredProjection.provenance,
    ...longTermProjection.provenance,
    ...(recentProjection === undefined ? [] : recentProjection.provenance),
    ...interpretations.flatMap((interpretation) => interpretation.provenance)
  ]);

  return Object.freeze({
    projectionVersion: P8_1C_VERSION,
    address: authoredProjection.address,
    identity: authoredProjection.identity,
    persona: authoredProjection.persona,
    longTermEvidence: longTermProjection,
    ...(recentProjection === undefined ? {} : { recentConversation: recentProjection }),
    interpretations: Object.freeze(interpretations),
    provenance: Object.freeze(provenance)
  });
}

function adaptMemoryEvent(
  event: MemoryEvent,
  expectedScopeReference: P8EvidenceScopeReference
): P8AuthorizedEvidence {
  if (event.scope !== expectedScopeReference.reference) {
    throw new Error(`P8 memory evidence scope is not authorized: ${event.id}.`);
  }

  const sourceClass = memorySourceClass(event);
  return createP8AuthorizedEvidence({
    evidenceReference: event.id,
    statement: event.content,
    sourceClass,
    channel: "LONG_TERM_EVIDENCE",
    support: memorySupport(event, sourceClass),
    scopeReference: expectedScopeReference,
    ...optionalSuppliedAt(event)
  });
}

function adaptRecentMessage(
  message: P8RecentConversationMessageInput,
  expectedScopeReference: P8EvidenceScopeReference
): P8AuthorizedEvidence {
  if (message.scopeReference.reference !== expectedScopeReference.reference) {
    throw new Error(`P8 recent conversation scope is not authorized: ${message.messageReference}.`);
  }
  if (message.role !== "user" && message.role !== "assistant") {
    throw new Error(`P8 recent conversation role is not recognized: ${message.messageReference}.`);
  }

  return createP8AuthorizedEvidence({
    evidenceReference: recentEvidenceReference(message.messageReference),
    statement: message.content,
    sourceClass:
      message.role === "assistant" ? "ASSISTANT_MODEL_GENERATED" : "EXPLICIT_USER_ORIGINATED",
    channel: "RECENT_CONVERSATION",
    support: message.role === "assistant" ? "NON_AUTHORITATIVE" : "DIRECT",
    scopeReference: expectedScopeReference,
    ...(message.suppliedAt === undefined ? {} : { suppliedAt: message.suppliedAt })
  });
}

export function recentEvidenceReference(messageReference: string): string {
  validateText(messageReference, "recent conversation messageReference", 120);
  return `recent-conversation:${messageReference}`;
}

function memorySourceClass(
  event: MemoryEvent
):
  | "EXPLICIT_USER_ORIGINATED"
  | "VERIFIED_SUPPORTED"
  | "OBSERVED_INTERACTION"
  | "WEAK_INFERRED"
  | "ASSISTANT_MODEL_GENERATED" {
  switch (event.assertion?.source) {
    case "assistant":
      return "ASSISTANT_MODEL_GENERATED";
    case "user":
      return "EXPLICIT_USER_ORIGINATED";
    case "system":
      return event.assertion.verification === "verified" ? "VERIFIED_SUPPORTED" : "WEAK_INFERRED";
    case "mixed":
    case "unknown":
      return "WEAK_INFERRED";
    default:
      return event.kind === "interaction" ? "OBSERVED_INTERACTION" : "WEAK_INFERRED";
  }
}

function memorySupport(
  event: MemoryEvent,
  sourceClass:
    | "EXPLICIT_USER_ORIGINATED"
    | "VERIFIED_SUPPORTED"
    | "OBSERVED_INTERACTION"
    | "WEAK_INFERRED"
    | "ASSISTANT_MODEL_GENERATED"
): "DIRECT" | "LIMITED" | "NON_AUTHORITATIVE" {
  if (sourceClass === "ASSISTANT_MODEL_GENERATED") {
    return "NON_AUTHORITATIVE";
  }
  if (
    (sourceClass === "EXPLICIT_USER_ORIGINATED" || sourceClass === "VERIFIED_SUPPORTED") &&
    event.assertion?.verification === "verified"
  ) {
    return "DIRECT";
  }
  return "LIMITED";
}

function optionalSuppliedAt(event: MemoryEvent): { suppliedAt?: string } {
  const suppliedAt = [event.occurredAt, event.observedAt, event.recordedAt].find(
    (candidate): candidate is string => typeof candidate === "string" && candidate.length > 0
  );
  return suppliedAt === undefined ? {} : { suppliedAt };
}

function projectEvidenceChannel(outcome: P8EvidenceAccessOutcome): P8EvidenceChannelProjection {
  return Object.freeze({
    accessStatus: outcome.status,
    status: epistemicStatusForAccess(outcome.status),
    evidenceCount: outcome.evidence.length,
    provenance: Object.freeze(outcome.evidence.map((evidence) => evidence.provenance))
  });
}

function epistemicStatusForAccess(status: P8EvidenceAccessStatus): P8EpistemicState {
  switch (status) {
    case "SUCCESS_WITH_EVIDENCE":
      return "UNKNOWN";
    case "SUCCESS_WITH_NO_RELEVANT_EVIDENCE":
      return "EMPTY";
    case "PARTIAL":
      return "PARTIAL";
    case "UNAVAILABLE":
      return "UNAVAILABLE";
    case "ERROR":
      return "ERROR";
  }
}

function accessStatusForCandidate(
  candidate: P8InterpretationCandidateInput,
  longTerm: P8AdaptedEvidenceAccess,
  recent: P8AdaptedEvidenceAccess | undefined,
  allEvidence: readonly P8AuthorizedEvidence[]
): P8EvidenceAccessStatus {
  const links = candidate.evidenceLinks ?? [];
  const linkedEvidence = links.map((link) => {
    const evidence = allEvidence.find(
      (candidateEvidence) => candidateEvidence.evidenceReference === link.evidenceReference
    );
    if (evidence === undefined) {
      throw new Error(
        `P8 interpretation evidence link references unavailable evidence: ${link.evidenceReference}.`
      );
    }
    return evidence;
  });
  const linkedRecent = linkedEvidence.some(
    (evidence) => evidence.channel === "RECENT_CONVERSATION"
  );
  const linkedLongTerm = linkedEvidence.some(
    (evidence) => evidence.channel === "LONG_TERM_EVIDENCE"
  );

  if (linkedLongTerm && longTerm.outcome.status === "PARTIAL") {
    return "PARTIAL";
  }
  if (linkedLongTerm && longTerm.outcome.status === "UNAVAILABLE") {
    return "UNAVAILABLE";
  }
  if (linkedLongTerm && longTerm.outcome.status === "ERROR") {
    return "ERROR";
  }
  if (linkedRecent && recent?.outcome.status === "PARTIAL") {
    return "PARTIAL";
  }
  if (linkedRecent && recent?.outcome.status === "UNAVAILABLE") {
    return "UNAVAILABLE";
  }
  if (linkedRecent && recent?.outcome.status === "ERROR") {
    return "ERROR";
  }
  if (links.length > 0 || allEvidence.length > 0) {
    return "SUCCESS_WITH_EVIDENCE";
  }
  if (longTerm.outcome.status !== "SUCCESS_WITH_EVIDENCE") {
    return longTerm.outcome.status;
  }
  return recent?.outcome.status ?? "SUCCESS_WITH_NO_RELEVANT_EVIDENCE";
}

function assertUniqueEvidenceReferences(evidence: readonly P8AuthorizedEvidence[]): void {
  const references = new Set<string>();
  for (const atom of evidence) {
    if (references.has(atom.evidenceReference)) {
      throw new Error(`P8 adapted evidence reference must be unique: ${atom.evidenceReference}.`);
    }
    references.add(atom.evidenceReference);
  }
}

function uniqueProvenance(
  provenance: readonly P8SemanticProvenanceReference[]
): P8SemanticProvenanceReference[] {
  const unique = new Map<string, P8SemanticProvenanceReference>();
  for (const reference of provenance) {
    unique.set(provenanceKey(reference), reference);
  }
  return [...unique.values()].sort((left, right) =>
    provenanceKey(left).localeCompare(provenanceKey(right))
  );
}

function provenanceKey(reference: P8SemanticProvenanceReference): string {
  if (reference.source === "authored") {
    return [reference.source, reference.reference, reference.revision ?? ""].join("\u0000");
  }
  return [
    reference.source,
    reference.reference,
    reference.scopeReference.reference,
    reference.channel,
    reference.sourceClass,
    reference.suppliedAt ?? "",
    reference.contradictionReferences.join(",")
  ].join("\u0000");
}

function validateScopeReference(input: P8EvidenceScopeReference): P8EvidenceScopeReference {
  validateText(input.reference, "evidence scope reference", 160);
  return Object.freeze({ reference: input.reference });
}

function validateNonNegativeInteger(value: number, field: string): void {
  if (!Number.isInteger(value) || value < 0) {
    throw new Error(`P8 ${field} must be a non-negative integer.`);
  }
}

function validateText(value: string, field: string, maximum: number): void {
  if (typeof value !== "string" || value.length === 0 || value.length > maximum) {
    throw new Error(`P8 ${field} must be a non-empty string of at most ${maximum} characters.`);
  }
}
