#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"
export YUVI_RUNTIME_ENV_DIR="$repo_root"

state_dir="${XDG_RUNTIME_DIR:-/tmp}/yuvi-runtime-dev"
mkdir -p "$state_dir"

server_pid_file="$state_dir/server.pid"
web_pid_file="$state_dir/web.pid"
server_log="$state_dir/server.log"
web_log="$state_dir/web.log"
restart_marker="$state_dir/restart-request.json"

server_url="http://localhost:6121"
web_host="${YUVI_WEB_HOST:-${WEB_HOST:-127.0.0.1}}"
web_port="${YUVI_WEB_PORT:-${WEB_PORT:-5173}}"
web_url="http://$web_host:$web_port"
websocket_url="ws://localhost:6121/ws"

add_node_path() {
  if command -v node >/dev/null 2>&1 && command -v pnpm >/dev/null 2>&1; then
    return
  fi

  if [ -d "$HOME/.nvm/versions/node" ]; then
    local node_bin
    node_bin="$(find "$HOME/.nvm/versions/node" -mindepth 3 -maxdepth 3 -type f -name node -printf '%h\n' | sort -V | tail -n 1 || true)"
    if [ -n "$node_bin" ]; then
      export PATH="$node_bin:$PATH"
    fi
  fi
}

require_tool() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "缺少必要工具：$1" >&2
    exit 1
  fi
}

is_running() {
  local pid_file="$1"
  [ -f "$pid_file" ] && kill -0 "$(cat "$pid_file")" >/dev/null 2>&1
}

check_file_presence() {
  if [ -f ".env.example" ]; then
    echo "已找到 .env.example"
  else
    echo "缺少 .env.example" >&2
    exit 1
  fi

  if [ -f ".env" ]; then
    echo "已找到 .env（不会打印内容）"
  else
    echo "警告：未找到 .env；请运行 cp .env.example .env 后填写本地配置。" >&2
    echo "开发模式将继续使用当前 shell 环境；mock fallback 仅在 PROVIDER_ALLOW_MOCKS=true 时启用。" >&2
  fi
}

load_env_file() {
  if [ -f ".env" ]; then
    echo "[env] Loaded .env（不会打印内容）"
    set -a
    # .env is local developer state. Keep it shell-compatible and never commit it.
    # shellcheck disable=SC1091
    . ./.env
    set +a
  fi

  if [ -f ".env.local" ]; then
    echo "[env] Loaded .env.local（不会打印内容，覆盖 .env 中的同名变量）"
    set -a
    # .env.local is generated by Dashboard Settings and stays local.
    # shellcheck disable=SC1091
    . ./.env.local
    set +a
  fi
}

start_infra() {
  if [ "${SKIP_INFRA:-0}" = "1" ]; then
    echo "SKIP_INFRA=1 set; skipping Docker infrastructure startup."
    echo "适用于 MEMORY_REPOSITORY=in-memory 的轻量开发。"
    return
  fi

  if [ -f "infra/docker-compose.yml" ]; then
    echo "启动 Docker infra..."
    docker compose -f infra/docker-compose.yml up -d
  else
    echo "未找到 infra/docker-compose.yml，跳过 Docker infra"
  fi
}

install_dependencies_if_needed() {
  if [ ! -d "node_modules" ]; then
    echo "未找到 node_modules，执行 pnpm install..."
    pnpm install
  else
    echo "已找到 node_modules，跳过 pnpm install"
  fi
}

run_auto_migrate_if_needed() {
  if [ "${MEMORY_REPOSITORY:-in-memory}" != "postgres" ]; then
    return
  fi
  if [ -z "${DATABASE_URL:-}" ]; then
    echo "MEMORY_REPOSITORY=postgres but DATABASE_URL is not configured; skipping db:migrate." >&2
    return
  fi
  if [ "${YUVI_AUTO_MIGRATE:-1}" = "0" ]; then
    echo "YUVI_AUTO_MIGRATE=0 set; skipping db:migrate."
    return
  fi
  echo "Running pnpm db:migrate for PostgreSQL memory（不会打印 DATABASE_URL）..."
  pnpm db:migrate
}

server_command() {
  env \
    NODE_ENV="${NODE_ENV:-development}" \
    YUVI_RUNTIME_ENV_DIR="$YUVI_RUNTIME_ENV_DIR" \
    YUVI_DEV_SUPERVISOR="${YUVI_DEV_SUPERVISOR:-0}" \
    YUVI_AUTO_MIGRATE="${YUVI_AUTO_MIGRATE:-1}" \
    YUVI_RESTART_MARKER="$restart_marker" \
    PROVIDER_ALLOW_MOCKS="${PROVIDER_ALLOW_MOCKS:-false}" \
    MEMORY_REPOSITORY="${MEMORY_REPOSITORY:-in-memory}" \
    SERVER_HOST="${SERVER_HOST:-127.0.0.1}" \
    SERVER_PORT="${SERVER_PORT:-6121}" \
    bash -c 'cd apps/server && exec ../../node_modules/.bin/tsx --conditions development src/index.ts'
}

start_server() {
  if [ ! -f "apps/server/package.json" ]; then
    echo "未找到 apps/server，跳过 server"
    return
  fi

  if is_running "$server_pid_file"; then
    echo "Server 已在运行，PID $(cat "$server_pid_file")"
    return
  fi

  echo "启动 Server: $server_url"
  echo "Provider fallback: PROVIDER_ALLOW_MOCKS=${PROVIDER_ALLOW_MOCKS:-false} (real-provider-first unless explicitly true)"
  run_auto_migrate_if_needed
  if [ "${YUVI_DEV_SUPERVISOR:-0}" = "1" ]; then
    setsid bash -c '
      set -euo pipefail
      repo_root="$1"
      restart_marker="$2"
      while true; do
        rm -f "$restart_marker"
        cd "$repo_root/apps/server"
        set +e
        NODE_ENV="${NODE_ENV:-development}" \
        YUVI_RUNTIME_ENV_DIR="$repo_root" \
        YUVI_DEV_SUPERVISOR=1 \
        YUVI_AUTO_MIGRATE="${YUVI_AUTO_MIGRATE:-1}" \
        YUVI_RESTART_MARKER="$restart_marker" \
        PROVIDER_ALLOW_MOCKS="${PROVIDER_ALLOW_MOCKS:-false}" \
        MEMORY_REPOSITORY="${MEMORY_REPOSITORY:-in-memory}" \
        SERVER_HOST="${SERVER_HOST:-127.0.0.1}" \
        SERVER_PORT="${SERVER_PORT:-6121}" \
        ../../node_modules/.bin/tsx --conditions development src/index.ts
        code=$?
        set -e
        if [ "$code" != "42" ] && [ ! -f "$restart_marker" ]; then
          exit "$code"
        fi
        echo "[supervisor] Deep restart requested; reloading env and restarting."
        cd "$repo_root"
        set -a
        [ -f .env ] && . ./.env
        [ -f .env.local ] && . ./.env.local
        set +a
        if [ "${MEMORY_REPOSITORY:-in-memory}" = "postgres" ] && [ -n "${DATABASE_URL:-}" ] && [ "${YUVI_AUTO_MIGRATE:-1}" != "0" ]; then
          pnpm db:migrate
        fi
        sleep 1
      done
    ' supervisor "$repo_root" "$restart_marker" >"$server_log" 2>&1 < /dev/null &
  else
    setsid bash -c "$(declare -f server_command); server_command" >"$server_log" 2>&1 < /dev/null &
  fi

  echo "$!" > "$server_pid_file"

  wait_for_server
}

start_web() {
  if [ ! -f "apps/web/package.json" ]; then
    echo "未找到 apps/web，跳过 Web UI"
    return
  fi

  if is_running "$web_pid_file"; then
    echo "Web UI 已在运行，PID $(cat "$web_pid_file")"
    return
  fi

  if [ "$web_host" = "0.0.0.0" ]; then
    echo "警告：YUVI_WEB_HOST=0.0.0.0 会将开发 Dashboard 暴露到局域网。" >&2
  fi

  echo "启动 Web UI: $web_url"
  setsid bash -c 'cd apps/web && exec pnpm dev' >"$web_log" 2>&1 < /dev/null &

  echo "$!" > "$web_pid_file"
  sleep 2

  if ! is_running "$web_pid_file"; then
    echo "Web UI 启动失败，最近日志：" >&2
    tail -n 80 "$web_log" >&2 || true
    exit 1
  fi
}

wait_for_server() {
  for _ in $(seq 1 20); do
    if ! is_running "$server_pid_file"; then
      echo "Server 启动失败，最近日志：" >&2
      tail -n 80 "$server_log" >&2 || true
      rm -f "$server_pid_file"
      exit 1
    fi

    if command -v curl >/dev/null 2>&1 && curl --fail --silent --show-error "$server_url/health" >/dev/null 2>&1; then
      echo "Server health check 通过"
      return
    fi

    sleep 1
  done

  echo "Server 已启动但 /health 暂未通过，最近日志：" >&2
  tail -n 80 "$server_log" >&2 || true
  exit 1
}

add_node_path

echo "检查开发工具..."
require_tool node
require_tool pnpm
require_tool setsid
if [ "${SKIP_INFRA:-0}" != "1" ]; then
  require_tool docker
  docker compose version >/dev/null
fi

node --version
pnpm --version
if [ "${SKIP_INFRA:-0}" != "1" ]; then
  docker --version
  docker compose version
fi

check_file_presence
load_env_file
start_infra
install_dependencies_if_needed
start_server
start_web

echo
echo "开发服务已启动："
echo "  Server:    $server_url"
echo "  Web UI:    $web_url"
echo "  WebSocket: $websocket_url"
echo
echo "日志目录：$state_dir"
echo "检查状态：./scripts/health.sh"
echo "停止服务：./scripts/stop.sh"
